DROP TABLE IF EXISTS leads;

CREATE TABLE IF NOT EXISTS leads (
    accepts_financial_aid 	text,
    ages_served 	text,
    capacity 	real, 
    certificate_expiration_date	integer, 
    city 	text,
    address1 	text,
    address2 	text,
    company 	text,
    phone 	text,
    phone2 	text,
    county 	text,
    curriculum_type 	text,
    email 	text,
    first_name 	text,
    language	text,
    last_name	text,
    license_status	text,
    license_issued	integer, 
    license_number	real, 
    license_renewed	integer, 
    license_type	text,
    max_age	real, 
    min_age	real, 
    operator	text,
    provider_id	text,
    schedule	text,
    state	text,
    title	text,
    website_address	text,
    zip	text,
    facility_type	text,
    is_active 
)